### ISSUE TITLE
P2981: Johel to fill "6.9 non-negative quantities"

### ISSUE THREAD

**Issue by JohelEGP** [mpusz/wg21-papers#33]
Starting point: <https://github.com/mpusz/mp-units/issues/468#issuecomment-1705317626>.

**Comment by JohelEGP** [comment]
§6 Safety Features says
> This chapter will describe the features that enforce safety in our code bases.

It seems that "non-negative quantities" is the only sub-chapter of §6 that isn't a safety feature.
Should I move it to [7 Safety Pitfalls](https://mpusz.github.io/wg21-papers/papers/2981R0_improving_our_safety_with_a_physical_quantities_and_units_library.html#safety-pitfalls)?

**Comment by mpusz** [comment]
Why do you think it is not a safety feature? The chapter introduction does not claim to provide compile-time safety, and in my opinion, contract checks are about safety as well.

**Comment by JohelEGP** [comment]
I just haven't convinced myself that having to explicitly opt into the property of "non-negative" is a safety feature.
It is a safety feature being able to do it,
and it is a usability feature being able to not require it.
But as I mention at <https://github.com/mpusz/mp-units/issues/468#issuecomment-1758148563> and <https://github.com/mpusz/mp-units/issues/468#issuecomment-1758340180>,
there are also safety pitfalls lurking,
so I think we still another chapter for non-negative quantities in [7 Safety Pitfalls](https://mpusz.github.io/wg21-papers/papers/2981R0_improving_our_safety_with_a_physical_quantities_and_units_library.html#safety-pitfalls).

**Comment by mpusz** [comment]
If you would like to provide another chapter in Pitfalls, please add it.

In case anyone sees something missing, please feel free to add more content to papers.
