### ISSUE TITLE
"Title Case" or "Sentence case" titles

### ISSUE THREAD

**Issue by JohelEGP** [mpusz/wg21-papers#42]
H&D has mixed case spelling for titles.
Some chapters use "Tile Case".
Others use "Sentence case".
- [x] Please, choose your one true way.
I suggest "Sentence case".
- [x] Please, review the other papers for this issue.

**Comment by mpusz** [comment]
LOL, it seems I was mostly using "Title Case" for chapters and "Sentence case" for subchapters. But I was not very consistent even in this approach 😜 

I will change to "Sentence case" as recommended.

**Comment by mpusz** [comment]
Fixed! Thanks for pointing this out!
